name: JustReports
version: '${version}'
main: me.fortibrine.justreports.JustReportsPlugin
api-version: 1.13

permissions:
  justreports.*:
    default: false
    children:
      - justreports.report
      - justreports.reports
      - justreports.reports.answer
      - justreports.see
      - justreports.reputation
      - justreports.reputation.other
      - justreports.reload
  justreports.report:
    default: true
  justreports.reports:
    default: op
  justreports.reports.answer:
    default: op
  justreports.see:
    default: op
  justreports.reputation:
    default: op
  justreports.reputation.other:
    default: op
  justreports.reload:
    default: op
